name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release

    - name: dotnet publish
      run: dotnet publish ./eShopOnWeb.sln -c Release -o release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
          # Artifact name
          name: Application_Artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/eShopOnWeb/eShopOnWeb/release
            
  deploy:
    runs-on: windows-latest
    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
          - name: Download a Build Artifact
            uses: actions/download-artifact@v4.1.8
            with:  
              name: Application_Artifact

          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'selvanoneclickdemo'
              slot-name: 'Production'
              publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
              package: .
                
            
